### ISSUE TITLE
active.open_and_wait_until_communicating return  False

### ISSUE THREAD

**Issue by sazima** [kenta-shimizu/pysemisecs#3]
```
 active.open()
r = active.open_and_wait_until_communicating(5)
active.add_recv_all_msg_listener(self._recv_all_msg_listener)
# self._send_hand_shake(active)
if not r:
    get_logger().warn('connect open_and_wait_until_communicating return false')
```
The method `open_and_wait_until_communicating` returns false. What is the general reason for this

**Comment by kenta-shimizu** [comment]
Hi,
I guess that HSMS-SS-state wasn't SELECTED in timeout.

Return True if communicating success.
HSMS-SS-communicating-success is SELECTED state.
Otherwise return False.

If parameter 'timeout' is None, blocking until communicating success, return True.
If parameter 'timeout' is Number value, waiting for timeout value, and return result.

This method is not published in 'README.md'. because the explanation is too long.
I am happy to have found this method.

Thanks regards.
