### ISSUE TITLE
Large send_sml() string causes to go into an infinite loop

### ISSUE THREAD

**Issue by jmackos** [kenta-shimizu/pysemisecs#5]
I am trying to implement a large send_sml()

**Comment by kenta-shimizu** [comment]
Hi,
thanks for issue report.

I'll look into this issue now.
But I forgot python and this repository so it will take some time.

Best regards.

**Comment by kenta-shimizu** [comment]
Tested.
- secs.HsmsSsActiveCommunicator #send_sml short and long SML.
- secs.Secs1OnTcpIpCommunicator #send_sml short and long SML.

Result: good. no problem.
I suspected a failure in SECS-I message block division, but it turned out to be successful.

NOT test.
- secs.Ses1OnPySerialCommunicator #send_sml

I don't have Serial-port PC. I use RaspberryPi to test SECS-I. I can't try it right away.

**Comment by kenta-shimizu** [comment]
I also suspect a USB-Serial-Converter.
SECS-I block send/receive requires 257 bytes of cache.
Communication may fail with cheap ones. (I have also encountered.)
I only buy FTDI chip USB-Serial-Converters.

**Comment by jmackos** [comment]
Yes, I am using secs.Ses1OnPySerialCommunicator.

I will try better USB-serial-converter.  And see if that helps.  Thank you for testing! I will mark issue resolved.
